kind: Deployment
apiVersion: apps/v1
metadata:
   name: consult
spec:
   replicas: 2
   selector:      # tells the controllers which pods to watch/belong to now
    matchLabels:
     app: consult
   template:
      metadata:
        labels:
          app: consult
      spec:
       containers:
        - name: consult
          image: vikashashoke/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80