kind: Service                             
apiVersion: v1
metadata:
  name: consult
  labels:
    app: consult
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: consult                    
  type: LoadBalancer     